### ISSUE TITLE
Update DEX to Uniswap V3 Design

### ISSUE THREAD

**Issue by balqaasem** [setheum/setheum#228]
Follows Uniswap V3 design.
Reference: https://docs.uniswap.org/concepts/introduction/liquidity-user-guide
Checks these
- [ ] DEX - Add price_range to set price range #221
- [ ] DEX - Add starting_price when listing new pool - "select starting price" #220
- [ ] DEX - Add fee-tier to support "multiple fee tiers per pool" like Uniswap V3 #219
- [ ] DEX - Add strategies to DEX like in UniswapV3 #223

**Comment by balqaasem** [comment]
I have designed a much better price range technology in Setheum. Will implement that.
Ref: #384
